name = "ilia-website"
main = "index.html" 

[env.production]
vars = { }

# افزایش زمان timeout برای جلوگیری از خطای 522
[env.production.durable_objects]
timeout = 60000

# تنظیمات دیپلوی
[env.production.deploy]
include = ["*.html", "*.css", "*.js", "*.png", "*.json", "*.xml", "*.txt"]
